### ISSUE TITLE
Connected to database but got an error

### ISSUE THREAD

**Issue by Pelayori003** [ImagicTheCat/vRP-db-drivers#2]
The error shows after connecting to db:

[vRP] Connected to DB using driver "ghmattimysql".
Error resuming coroutine: @vrp/lib/utils.lua:45: error loading module vrp_ghmattimysql/init_vrp:@vrp/lib/utils.lua:69: async wait(): Citizen.Await returned (nil) before the areturn call.
stack traceback:
        [C]: in function 'error'
        @vrp/lib/utils.lua:69: in function <@vrp/lib/utils.lua:63>
        (...tail calls...)
        [string "vrp/vRP.lua"]:131: in method 'registerDBDriver'
        [string "vrp_ghmattimysql/init_vrp.lua"]:65: in main chunk
        [C]: in function 'xpcall'
        @vrp/lib/utils.lua:40: in function 'module'
        @vrp/base.lua:14: in local 'f'
        [string "vrp/lib/Proxy.lua"]:59: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        @vrp/lib/utils.lua:45: in function 'module'
        @vrp/base.lua:14: in local 'f'
        [string "vrp/lib/Proxy.lua"]:59: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP
