### ISSUE TITLE
async wait(): Citizen.Await ret    urned (nil) before the areturn call.

### ISSUE THREAD

**Issue by TheyCallMeAle** [ImagicTheCat/vRP-db-drivers#3]
Hi, give me this error:

Error resuming coroutine: @vrp/lib/utils.lua:69: async wait(): Citizen.Await ret    urned (nil) before the areturn call.
stack traceback:
        [C]: in function 'error'
        @vrp/lib/utils.lua:69: in function <@vrp/lib/utils.lua:63>
        (...tail calls...)
        [string "vrp/vRP.lua"]:131: in method 'registerDBDriver'
        [string "vrp_ghmattimysql/init_vrp.lua"]:66: in function <[string "vrp_g    hmattimysql/init_vrp.lua"]:65>

I have all the recent files, including his fix, and he gave me that error

I'll wait for an answer.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP/tree/master/doc#installation
