### ISSUE TITLE
uppercase letters are wrong

### ISSUE THREAD

**Issue by nappel4life** [ImagicTheCat/vRP-db-drivers#4]
New:
-- METHODS

function DBDriver:onInit(cfg)
  self.queries = {}
  self.API = exports["ghmattimysql"]
  if self.API then
    self.API:Query("SELECT 1") -- multiple Buffer issue fix
  end
  return self.API ~= nil
end

Old:
> -- METHODS

>function DBDriver:onInit(cfg)
>  self.queries = {}
>  self.API = exports["GHMattiMySQL"]
>  if self.API then
>    self.API:Query("SELECT 1") -- multiple Buffer issue fix
>  end
  return self.API ~= nil
end

**Comment by ImagicTheCat** [comment]
Wrong ? More details needed.

**Comment by nappel4life** [comment]
If GHMattiMySQL in uppercase letters so came the errors "[vRP] DB driver “ghmattimysql” not initialized yet (39 prepares cached, 6 queries cached)." bla bla.. At windows 10. If i write these "ghmttimysql" in lowercase letters then is no more error. 
sry for my bad english

**Comment by nappel4life** [comment]
ah in file init_vrp.lua at line 17

**Comment by ImagicTheCat** [comment]
I think you had a false positive, you should have an error if the export was not working anymore.

**Comment by ImagicTheCat** [comment]
You are probably using the wrong GHMattiMySQL version.
