### ISSUE TITLE
Probleme DataBase

### ISSUE THREAD

**Issue by EliotPC0** [ImagicTheCat/vRP-db-drivers#5]
[https://imgur.com/a/i7zDQA5](url) Bonjour j'ai remarqué que vous parlez français c'est pourquoi je me permet de vous contacter en français suite à un problème de connexion à la base de donnée.
J'ai enregistrer les informations de la base donnée dans vrp est GHMattiMySQL j'ai ensuite copier les lignes de [https://github.com/ImagicTheCat/fivem/tree/scheduler/data/shared/citizen/scripting/lua](url) dans fx server mais j'ai toujours le problème.

**Comment by ImagicTheCat** [comment]
Vous n'êtes pas le premier avec le problème, mais les issues GitHub ne servent qu'aux bug/features, pour l'aide à l'utilisation il faut voir le discord/le sujet vRP (FiveM).
