### ISSUE TITLE
Making the driver compatible with latest GHMattiMySQL?

### ISSUE THREAD

**Issue by TheDumpap** [ImagicTheCat/vRP-db-drivers#6]
Would you be able to modify the db driver to be compatible with the new GHMattiMySQL (https://github.com/GHMatti/ghmattimysql)? :)

**Comment by ImagicTheCat** [comment]
A GHMattiMySQL JS driver can be created, may do it but don't know when. Until then, if people use GHMattiMySQL JS, they can create one and do a pull request.

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/vRP-db-drivers/commit/497d287fe68158dd9740af88368e0f02b22620e7
